{
  "formatVersion": "1.1",
  "component": {
    "group": "uploadapkplugin",
    "module": "app",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "app-unspecified.jar",
          "url": "app-unspecified.jar",
          "size": 36367,
          "sha512": "a77055aa6ecbd7d28fba76ebe89eb8e1cbae4266e489b3dc482778cb69169fa253dbe0091f55672b9b5afd5ae235834d5eee63dfffcdaafc2c20db3c5494b8b7",
          "sha256": "7a2446ca584281d76a1dd539d7d412f7075279f47991955e7165c61831214786",
          "sha1": "6e5fbd734581f465167256ac5e69ce58072e1961",
          "md5": "cccaa0dcafa9b64122828864c05bf8fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.4"
          }
        },
        {
          "group": "com.github.dcendents",
          "module": "android-maven-gradle-plugin",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.12"
          }
        }
      ],
      "files": [
        {
          "name": "app-unspecified.jar",
          "url": "app-unspecified.jar",
          "size": 36367,
          "sha512": "a77055aa6ecbd7d28fba76ebe89eb8e1cbae4266e489b3dc482778cb69169fa253dbe0091f55672b9b5afd5ae235834d5eee63dfffcdaafc2c20db3c5494b8b7",
          "sha256": "7a2446ca584281d76a1dd539d7d412f7075279f47991955e7165c61831214786",
          "sha1": "6e5fbd734581f465167256ac5e69ce58072e1961",
          "md5": "cccaa0dcafa9b64122828864c05bf8fd"
        }
      ]
    }
  ]
}
